[2024-03-09T15:33:00.803+0000] {scheduler_job_runner.py:1766} ERROR - Detected zombie job: {'full_filepath': '/opt/airflow/dags/task1dag.py', 'processor_subdir': '/opt/airflow/dags', 'msg': "{'DAG Id': 'task1dag', 'Task Id': 'scrape_data_2019', 'Run Id': 'scheduled__2024-03-08T00:00:00+00:00', 'Hostname': 'dde2eb23f30a', 'External Executor Id': 'a1703142-a79f-412d-a7ac-5f2676ae3422'}", 'simple_task_instance': <airflow.models.taskinstance.SimpleTaskInstance object at 0x7f3e5bafa670>, 'is_failure_callback': True} (See https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/tasks.html#zombie-undead-tasks)
[2024-03-09T16:05:00.443+0000] {scheduler_job_runner.py:1586} WARNING - Marking task instance <TaskInstance: task1dag.scrape_data_2019 scheduled__2024-03-08T00:00:00+00:00 [queued]> stuck in queued as failed. If the task instance has available retries, it will be retried.
[2024-03-09T16:05:01.604+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: task1dag.scrape_data_2019 scheduled__2024-03-08T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
[2024-03-09T19:52:37.639+0000] {scheduler_job_runner.py:1766} ERROR - Detected zombie job: {'full_filepath': '/opt/airflow/dags/task1dag.py', 'processor_subdir': '/opt/airflow/dags', 'msg': "{'DAG Id': 'task1dag', 'Task Id': 'scrape_data_2019', 'Run Id': 'scheduled__2024-03-08T00:00:00+00:00', 'Hostname': '800ade8643a5', 'External Executor Id': '8c5f4e3d-440a-4ea3-85b7-82ca368f9e33'}", 'simple_task_instance': <airflow.models.taskinstance.SimpleTaskInstance object at 0x7fbfc7479d60>, 'is_failure_callback': True} (See https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/tasks.html#zombie-undead-tasks)
[2024-03-09T20:04:45.464+0000] {scheduler_job_runner.py:1766} ERROR - Detected zombie job: {'full_filepath': '/opt/airflow/dags/task1dag.py', 'processor_subdir': '/opt/airflow/dags', 'msg': "{'DAG Id': 'task1dag', 'Task Id': 'scrape_data_2019', 'Run Id': 'scheduled__2024-03-08T00:00:00+00:00', 'Hostname': '43465f8902fb', 'External Executor Id': 'f5f00e93-0513-4775-912a-108fb5c123a5'}", 'simple_task_instance': <airflow.models.taskinstance.SimpleTaskInstance object at 0x7f7982612e80>, 'is_failure_callback': True} (See https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/tasks.html#zombie-undead-tasks)
[2024-03-09T20:05:04.003+0000] {scheduler_job_runner.py:1766} ERROR - Detected zombie job: {'full_filepath': '/opt/airflow/dags/task1dag.py', 'processor_subdir': '/opt/airflow/dags', 'msg': "{'DAG Id': 'task1dag', 'Task Id': 'scrape_data_2019', 'Run Id': 'scheduled__2024-03-08T00:00:00+00:00', 'Hostname': '43465f8902fb', 'External Executor Id': 'f5f00e93-0513-4775-912a-108fb5c123a5'}", 'simple_task_instance': <airflow.models.taskinstance.SimpleTaskInstance object at 0x7f79827253a0>, 'is_failure_callback': True} (See https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/tasks.html#zombie-undead-tasks)
